### ISSUE TITLE
Predare la Mai Multe Grupe

### ISSUE THREAD

**Issue by dandragos** [unibuc-cs/software-engineering-product-topteam#17]
### User Story 14: Predare la Mai Multe Grupe
- Ca un profesor, vreau să am posibilitatea de a preda la mai multe grupe simultan, astfel încât să îmi pot gestiona eficient timpul și elevii.

#### Subtasks:
- [ ] Modificare profilului profesorilor pentru a permite gestionarea mai multor grupe
- [ ] Creare unei interfețe de administrare a grupelor pentru fiecare profesor
- [ ] Sistem de programare a lecțiilor, sincronizat cu grupele la care predă
- [ ] Vizualizare centralizată a elevilor și temelor din toate grupele

---
