### ISSUE TITLE
Vizualizare Cursuri și Teme

### ISSUE THREAD

**Issue by dandragos** [unibuc-cs/software-engineering-product-topteam#5]
### User Story 2: Vizualizare Cursuri și Teme
- Ca un elev, vreau să pot vizualiza cursurile și temele încărcate de profesor, astfel încât să pot accesa materialele necesare pentru învățare.
- Ca un profesor, vreau să încarc teme și lecții pentru grupurile mele de elevi, astfel încât să pot distribui materialele educaționale.

#### Subtasks:
- [ ] Listarea cursurilor pentru elevi
- [ ] Încărcarea temelor și cursurilor de către profesori
- [ ] Vizualizarea lecțiilor și temelor încărcate

---
