### ISSUE TITLE
Chat Elev-Profesor

### ISSUE THREAD

**Issue by dandragos** [unibuc-cs/software-engineering-product-topteam#8]
### User Story 5: Chat Elev-Profesor
- Ca un elev, vreau să pot comunica cu profesorul și colegii mei printr-un chat de grup, astfel încât să pot adresa întrebări și discuta subiecte de curs.
- Ca un profesor, vreau să pot răspunde elevilor din grupa mea pentru a le oferi feedback în timp real.

#### Subtasks:
- [ ] Sistem de chat integrat în platformă
- [ ] Opțiune de grup pentru elevi și profesori
- [ ] Notificări pentru mesaje noi

---
